apiVersion: v1
kind: Service
metadata:
  name: nextjs-sales-service
spec:
  selector:
    app: nextjs-sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: "192.168.1.91"